#!/usr/bin/env python3
"""Regenerate checked-in AA font tables; not needed for ordinary firmware builds.

Requires Pillow 12.2.0 and the specified DejaVu Sans 2.37 TTF files.
The exact input hashes are checked so a different system font cannot silently
change layout. Run from the repository root (see internal/uifont/README.md).
"""
import argparse
import hashlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, __version__


def checked(path, digest):
    if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
        raise SystemExit(f"Unexpected font SHA-256: {path}")
    return path


def quoted(data):
    return " +\n".join('"' + ''.join(f'\\x{v:02x}' for v in data[i:i+64]) + '"'
                         for i in range(0, len(data), 64)) or '""'


def make_font(name, path, size, first, last):
    font = ImageFont.truetype(str(path), size, layout_engine=ImageFont.Layout.BASIC)
    data, index = bytearray(), bytearray()
    for code in range(first, last+1):
        ch = chr(code)
        left, top, right, bottom = font.getbbox(ch, anchor='ls')
        width, height = right-left, bottom-top
        advance = round(font.getlength(ch))
        assert 0 <= width <= 255 and 0 <= height <= 255 and 0 <= advance <= 255
        assert -128 <= left <= 127 and -128 <= top <= 127
        index.extend(len(data).to_bytes(3, 'big'))
        data.extend((width, height, advance, left & 255, top & 255))
        if not width or not height:
            continue
        bitmap = Image.new('L', (width, height))
        ImageDraw.Draw(bitmap).text((-left, -top), ch, font=font, fill=255, anchor='ls')
        values = [(v*15+127)//255 for v in bitmap.tobytes()]
        if len(values) % 2:
            values.append(0)
        data.extend((a<<4)|b for a,b in zip(values[::2], values[1::2]))
    line_height = sum(font.getmetrics())
    return (f'var {name} = Font{{first:{first},last:{last},lineHeight:{line_height},\n'
            f'index:{quoted(index)},\ndata:{quoted(data)},\n}}\n')


def main():
    if __version__ != '12.2.0':
        raise SystemExit(f'Use Pillow 12.2.0 to reproduce the tables (found {__version__})')
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--regular', type=Path, default=Path('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
    parser.add_argument('--bold', type=Path, default=Path('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))
    parser.add_argument('--output', type=Path, default=Path('internal/uifont/data.go'))
    args = parser.parse_args()
    regular = checked(args.regular, 'ae7b7855e115a5966d8b1b3f80f254ccc117ec86f9965e202ee2940453837280')
    bold = checked(args.bold, '5c1247acef7f2b8522a31742c76d6adcb5569bacc0be7ceaa4dc39dd252ce895')
    result = '// Code generated by scripts/generate-fonts.py; DO NOT EDIT.\n'
    result += '// DejaVu Sans coverage data; see LICENSE.txt for font attribution.\npackage uifont\n\n'
    for name, path, size, first, last in (
        ('Regular18', regular, 18, 32, 126),
        ('Bold18', bold, 18, 32, 126),
        ('Bold24', bold, 24, 32, 126),
        ('Meridiem', regular, 14, 65, 80),
        ('Clock', bold, 60, 48, 58),
    ):
        result += make_font(name, path, size, first, last) + '\n'
    args.output.write_text(result)


if __name__ == '__main__':
    main()
